Repository pong-nyan/pong-nyan, pull requests merged in 2023-09, with the labels that each got.

#63 62 canvas 그림 입히기
  frontend/public/assets/flat-fish-left.png
  frontend/public/assets/flat-fish-right.png
  frontend/public/assets/flat-fish_orginal.png
  frontend/src/components/game/ScoreBoard.tsx
  frontend/src/matterEngine/matterJsUnit.ts
Labels: enhancement

#60 59 ball to loser
  frontend/src/context/socketGameEvent.ts
  frontend/src/matterEngine/matterJsGameEvent.ts
  frontend/src/matterEngine/matterJsSet.ts
Labels: enhancement

#69 feat(game): paddle density 변경
  frontend/src/matterEngine/matterJsUnit.ts
Labels: enhancement

#66 65 버튼 리다이렉션 붙이기
  frontend/src/components/button/NavButtonWrapper.tsx
  frontend/src/pages/channel/list.tsx
  frontend/src/styles/NavButtonWrapper.module.css
Labels: bug, help wanted

#82 76 message list make
  frontend/src/components/chat/ParticipatingChannelList.tsx
  frontend/src/pages/channel/message-channel-list.tsx
Labels: enhancement

#85 84 make public list page
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.module.ts
  backend/src/channel/channel.service.ts
  frontend/public/assets/lock.png
  frontend/public/assets/unlock.png
  frontend/src/components/chat/MakeChannel.tsx
  frontend/src/pages/channel/public-channel-list.tsx
  frontend/src/type.ts
Labels: enhancement

#83 80 게임 엔티디 생성 및 엔티디 업데이트 로직 구현
  backend/src/config/datasource.ts
  backend/src/entity/Game.ts
  backend/src/game/game.module.ts
  backend/src/game/game.service.ts
  frontend/src/components/game/logic/resumeGame.ts
  frontend/src/context/socketGameEvent.ts
Labels: enhancement

#103 101 plus button location set
  frontend/src/chat/components/MakeChannel.tsx
  frontend/src/chat/components/MakeChannelButton.tsx
  frontend/src/chat/styles/MakeChannel.module.css
  frontend/src/chat/styles/NavButtonWrapper.module.css
  frontend/src/pages/channel/list.tsx
  frontend/src/styles/globals.css
Labels: enhancement

#108 81 랭킹 페이지 만들기
  .vscode/settings.json
  frontend/src/pages/rank/index.tsx
  frontend/src/rank/components/RankUser.tsx
  frontend/src/rank/components/RankUserList.tsx
  frontend/src/rank/rankType.ts
  frontend/src/rank/styles/Rank.module.css
Labels: enhancement

#110 79 game matching 보완
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  backend/src/type/game.ts
  frontend/src/auth/components/FortyTwoIntraSignInButton.tsx
  frontend/src/context/socketGameEvent.ts
  frontend/src/context/useGetFetchData.ts
  frontend/src/game/components/CountDown.tsx
  frontend/src/game/components/End.tsx
  frontend/src/game/components/Run.tsx
  frontend/src/game/components/RunWrapper.tsx
  frontend/src/game/components/ScoreBoard.tsx
  frontend/src/game/logic/resumeGame.ts
  frontend/src/game/matterEngine/matterJsGameEvent.ts
  frontend/src/game/matterEngine/matterJsUnit.ts
  frontend/src/game/styles/Run.module.css
  frontend/src/pages/auth/index.tsx
  frontend/src/pages/auth/qr.tsx
Labels: enhancement

#107 feat(chat): makeChannel modal
  frontend/src/chat/components/MakeChannel.tsx
  frontend/src/chat/components/Modal.tsx
  frontend/src/pages/channel/list.tsx
  frontend/src/styles/globals.css
Labels: enhancement

#112 111 score logic 보완
  backend/src/game/game.gateway.ts
  backend/src/game/game.service.ts
  frontend/src/context/socketGameEvent.ts
  frontend/src/game/components/Run.tsx
  frontend/src/game/logic/resumeGame.ts
  frontend/src/game/matterEngine/matterJsGameEvent.ts
Labels: enhancement

#127 114 seperated user in channel
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.dto.ts
  backend/src/channel/channel.gateway.ts
  backend/src/channel/channel.guard.ts
  backend/src/channel/channel.module.ts
  backend/src/channel/channel.service.ts
  backend/src/type/channel.ts
  frontend/src/pages/channel/index.tsx
  frontend/src/pages/channel/list.tsx
  frontend/src/pages/channel/message-channel-list.tsx
  frontend/src/pages/channel/public-channel-list.tsx
Labels: enhancement

#131 style(chat): 백엔드 채팅파일구조 변경
  backend/src/app.module.ts
  backend/src/channel/channel.gateway.spec.ts
  backend/src/channel/channel.service.spec.ts
  backend/src/chat/channel.controller.ts
  backend/src/chat/channel.dto.ts
  backend/src/chat/channel.gateway.ts
  backend/src/chat/channel.guard.ts
  backend/src/chat/channel.module.ts
  backend/src/chat/channel.service.ts
  backend/src/chat/chat.gateway.spec.ts
  backend/src/chat/chat.service.spec.ts
Labels: enhancement

#142 133 쿠키받기 소켓id intraid 연동
  Makefile
  backend/src/app.gateway.ts
  backend/src/app.module.ts
  backend/src/auth/auth.guard.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/google2fa.controller.ts
  backend/src/auth/google2fa.gateway.ts
  backend/src/chat/channel.dto.ts
  backend/src/chat/channel.gateway.ts
  backend/src/chat/channel.module.ts
  backend/src/chat/channel.service.ts
  backend/src/game/game.dto.ts
  backend/src/game/game.module.ts
  backend/src/type/chatType.ts
  backend/src/type/userType.ts
  backend/src/user.module.ts
  backend/src/user.service.ts
  frontend/src/auth/components/Google2FA.tsx
  frontend/src/context/socket.ts
  share_type/chatType.ts
  share_type/gameType.ts
  share_type/socketType.ts
  share_type/userType.ts
Labels: enhancement

#153 120-프론트-메인-화면-구성
  backend/src/rank/rank.controller.ts
  frontend/src/_components/FeatureLinkList.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/FeatureLinkList.module.css
Labels: enhancement, frontend

#154 152 rank 쪽 타입 정리
  backend/src/app.module.ts
  backend/src/rank/rank.module.ts
  frontend/src/rank/components/RankUser.tsx
  frontend/src/type/rankType.ts
Labels: bug, backend

#159 143 setidmap setusermap를 이용하여 channel 로직 바꾸기
  backend/src/chat/channel.gateway.ts
  backend/src/chat/channel.service.ts
  backend/src/user.service.ts
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/components/MakeChannel.tsx
Labels: enhancement

#162 155 친구관리 페이지 초안 만들기
  frontend/src/friend/components/Manage.tsx
  frontend/src/friend/components/PendingFriend.tsx
  frontend/src/friend/components/PendingFriendList.tsx
  frontend/src/friend/components/RequestFriend.tsx
  frontend/src/friend/styles/Manage.module.css
  frontend/src/friend/styles/PendingFriend.module.css
  frontend/src/friend/styles/RequestFriend.module.css
  frontend/src/pages/friend/manage.tsx
  frontend/src/type/friendType.ts
Labels: enhancement, frontend

#169 164 seperated chatmessage with local storage
  backend/src/chat/channel.gateway.ts
  backend/src/type/chatType.ts
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/components/MessageList.tsx
  frontend/src/chat/utils/chatLocalStorage.ts
  frontend/src/type/chatType.ts
Labels: enhancement

#173 feat(chat): 링크로 채팅창에서 profile로 보내기
  frontend/src/chat/components/MessageList.tsx
Labels: enhancement

#190 189 채팅방 url로 구분하여 새로운 페이지에 출력
  backend/src/app.module.ts
  backend/src/chat/channel.controller.ts
  backend/src/chat/channel.gateway.ts
  backend/src/chat/channel.module.ts
  backend/src/chat/channel.service.ts
  backend/src/chat/chat.controller.ts
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  frontend/src/_components/FeatureLinkList.tsx
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatPrivateRoom.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/components/NavButtonWrapper.tsx
  frontend/src/chat/utils/chatLocalStorage.ts
  frontend/src/context/socket.ts
  frontend/src/pages/chat/[channelId].tsx
  frontend/src/pages/chat/list.tsx
  frontend/src/pages/chat/message-channel-list.tsx
  frontend/src/pages/chat/public-channel-list.tsx
Labels: enhancement

#194 38 game end event 구현하기
  backend/src/game/game.gateway.ts
  backend/src/type/userType.ts
  frontend/src/context/socketGameEvent.ts
  frontend/src/game/components/End.tsx
  frontend/src/game/components/Run.tsx
  frontend/src/game/components/RunWrapper.tsx
  frontend/src/game/components/Start.tsx
  frontend/src/game/matterEngine/matterJsGameEvent.ts
  frontend/src/game/styles/End.module.css
  frontend/src/pages/game/index.tsx
  frontend/src/type/gameType.ts
  frontend/src/type/userType.ts
Labels: enhancement

#197 191 use maxuser
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  backend/src/type/chatType.ts
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/utils/chatLocalStorage.ts
  frontend/src/context/socket.ts
  frontend/src/pages/chat/list.tsx
Labels: enhancement

#206 203 matching queue list 구현
  backend/src/app.gateway.ts
  backend/src/game/game.service.ts
Labels: enhancement

#219 205 권한관리
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/type/chatType.ts
Labels: enhancement

#232 231 disconnection 시 승자 1 점 부여 후 승리
  frontend/src/context/socketGameEvent.ts
  frontend/src/game/components/OriginPongRun.tsx
  frontend/src/game/components/Run.tsx
  frontend/src/game/components/RunWrapper.tsx
Labels: enhancement, frontend

#236 226 비밀번호 변경제거
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/components/MakeChannel.tsx
Labels: enhancement

#243 feat(chat): user Kick기능구현
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  frontend/src/chat/components/ChatRoom.tsx
Labels: enhancement

#266 247 chat kick ban
  backend/src/chat/chat.gateway.ts
  backend/src/chat/chat.service.ts
  backend/src/type/chatType.ts
  frontend/src/chat/components/ChannelList.tsx
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/type/chatType.ts
Labels: enhancement

#275 269 mute구현
  backend/src/chat/chat.gateway.ts
  frontend/src/chat/components/ChatRoom.tsx
Labels: enhancement

#283 feat(chat): block user 구현!
  backend/src/app.controller.ts
  backend/src/chat/chat.gateway.ts
  frontend/src/context/socketChatEvent.ts
  frontend/src/profile/components/RequesetBlock.tsx
Labels: enhancement

#284 281 채팅 channel 추가 보수
  frontend/src/chat/components/ChatRoom.tsx
  frontend/src/chat/components/MakeChannel.tsx
  frontend/src/chat/components/MessageInput.tsx
  frontend/src/chat/components/PrivateChannelLIst.tsx
  frontend/src/chat/components/PublicChannelList.tsx
  frontend/src/pages/_document.tsx
Labels: enhancement
